export const routeTitles = {
  "/Home_Reg": { title: "Home Menu", type: "HOME" },
  "/Home_Emy": { title: "Home Menu", type: "HOME" },
  "/Home_OPD": { title: "Home Menu", type: "HOME" },
  "/Home_ADT": { title: "Home Menu", type: "HOME" },
  "/Home_Invt": { title: "Home Menu", type: "HOME" },
  "/Home_Bill": { title: "Home Menu", type: "HOME" },
  "/Home_Enquiry": { title: "Home Menu", type: "HOME" },
  "/Home_Admin": { title: "Home Menu", type: "HOME" },
  "/Home_OT": { title: "Home Menu", type: "HOME" },
  "/Home_IPD": { title: "Home Menu", type: "HOME" },
  "/Home_Laundry": { title: "Home Menu", type: "HOME" },
  "/Home_Inventory": { title: "Home Menu", type: "HOME" },
  "/Home_MRD": { title: "Home Menu", type: "HOME" },
  "/Home_DietKitchen": { title: "Home Menu", type: "HOME" },
  "/Home_Global": { title: "Home Menu", type: "HOME" },
  "/change-password": { title: "Change Password", type: "NORMAL" },
  "/emergency/case-sheet": { title: "Emergency Case Sheet", type: "NORMAL" },
};